server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: amigoscode
    url: jdbc:postgresql://localhost:5432/fraud
    password: password
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: create-drop
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registery: true
    register-with-eureka: true